### ISSUE TITLE
conda activate no env completion?

### ISSUE THREAD

**Issue by hanfeicode** [tartansandal/conda-bash-completion#13] opened 2022-04-05 14:31 UTC
conda activate tab no env completion?

system info:
```
(demo) [root@web-devops-01 ~]# bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
(demo) [root@web-devops-01 ~]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

(demo) [root@web-devops-01 ~]# conda -V
conda 4.12.0
```

Q:
```
function __comp_conda_envs() {
    \local script="
    :    from __future__ import print_function;
    :    import json, os, sys;
    :    from os.path import isdir, join;
    :    print('\n'.join(
    :       d for ed in json.load(sys.stdin)['envs_dirs'] if isdir(ed)
    :       for d in os.listdir(ed) if isdir(join(ed, d))));
    "
    conda config --json --show envs_dirs | python -c "${script//    :    /}"
}
```

change to
```
function __comp_conda_envs() {
    conda env list | awk 'NR > 2 {print $1}'
}
```

```
            activate)
                #_filedir -d                     # environment directories  # note here!
                word_list=$(__comp_conda_envs 2>/dev/null)
                ;;
```
and then conda activate  work!

**Comment by tartansandal** [comment] 2022-04-07 02:55
Hi @hanfeicode, thanks for the query :smile: 

I'm assuming that when you trigger completion on `conda activate <tab>` you get a list of directories?

The problem here is the the first positional argument for the `activate` subcommand:

```console
$ conda activate --help
usage: conda activate [-h] [--[no-]stack] [env_name_or_prefix]

Activate a conda environment.

Options:

positional arguments:
  env_name_or_prefix    The environment name or prefix to activate. If the
                        prefix is a relative path, it must start with './'
                        (or '.\' on Windows).
...
```

So the argument can be either a _directory_ or an environment _name_.  I've made the completion merge the two which may be confusing if you run this from your home directory, because of the all the hidden directories show up. I've considered omitting the hidden directories, but I'm not sure if that is an acceptable compromise.

I used to use `conda env list` to get all the environments, but there was some convoluted issue where this would not always yield all the potential names, so I moved to the custom python script that fixes the issue. I can't remember the exact details of the bug, but I'm sure they are there in closed issue or the git log somewhere.  I probably should have put an explanatory note in the code. :wink:

**Comment by tartansandal** [comment] 2022-04-23 04:53
Hi @hanfeicode. I've not had any response to the last comments I made for a while now, so I'm going to assume the issue is resolved. Please feel free to reopen if this is not the case. :wink:

**Comment by dli417** [comment] 2022-04-26 20:23
Hi, I am also experiencing "conda activate" tab completion showing nothing at all. The code snippet from hanfeicode fixed it but you were saying there was a reason you are not using "conda env list" anymore, @tartansandal?

My system:
- GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
- Ubuntu 22.04 LTS
- conda 4.12.0 (auto_activate_base: false)
- conda-bash-completion installed by manually copying "conda" to ~/.local/share/bash-completion/completions/

**Comment by tartansandal** [comment] 2022-04-27 06:05
Hi @dli417 :smile: 

Thanks for the feedback! I've reopened the issue and added some new scripts that I use for testing installation in different environments (see the `docker` directory).

Your hint about setting `no_activate_base` seems to be cause of the issue. Will investigate some more and hopefully have solution for you soon.

**Comment by tartansandal** [comment] 2022-04-27 06:57
Good news @dli417 and @hanfeicode! I've tracked down and fixed the issue!  Fixes will be in the new 1.6 version which will sync up with conda-forge once all the CI bots have done their thing (could take a couple of days).

It would be fantastic if either of you could confirm the fix works for you so I can close the issue :)

**Comment by dli417** [comment] 2022-04-27 08:26
Hi @tartansandal, many thanks for the quick fix! I can confirm the new "conda" bash-completion works with my current setup now. I'm happy for the issue to be closed again.

**Closed** 2022-04-27 09:08 UTC

**Comment by tartansandal** [comment] 2022-07-24 07:57
Hi @dli417!

Just a heads up that the new `conda-bash-completion` v1.7 does completion for `conda activate` more like you would expect: completing for named environments by default, and only completing for paths if the stem looks like a path. :smile:

**Comment by dli417** [comment] 2022-07-24 09:53
Thanks for the mention @tartansandal,

The latest conda bash completion file from this GitHub repository (as I am manually copying it to my local bash completions directory) is working as described. I will definitely be using `conda/mamba activate` tab completion more instead of `conda/mamba env list` now! I think checking for the forward slash is a very elegant method to determine whether to complete named environments by default!

It is fantastic that the updated conda bash completion also makes your mamba bash completion script work the same way - thanks for keeping these scripts updated!
